### ISSUE TITLE
ReactNative開発環境構築

### ISSUE THREAD

**Issue by ikmzkro** [ikmz0104/React-Native#14]
- [ ] ReactNative TypeScriptでの環境構築
- [ ] eslint設定

**Comment by ikmz0104** [comment]
本PJからクローンしてきた

**Comment by ikmzkro** [comment]
iOSのみリリースしましょう
https://twitter.com/gundogan_vamos/status/1656080430037344258?s=20
- [x] Android Studio環境構築
